version: "3"

services:
  hslbot:
    build: .
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN:-}
      - SLACK_CHANNEL_ID=${SLACK_CHANNEL_ID:-}
      - MESSAGES_LANGUAGE=${MESSAGES_LANGUAGE:-en}
